server:
  port: 9005

spring:

  main:
    web-application-type: servlet

  application:
    name: ptarmigan-finance

  cloud:
    consul:
      host: 127.0.0.1
      port: 8500

      discovery:
        service-name: fiance



  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306
    username: root
    password: 123456

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
