server:
  port: 8989

spring:

  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      ribbon:
        enabled: true
      discovery:
        service-name: payment

    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
        port: 8719


  zipkin:
    base-url: http://127.0.0.1:9411/
    discovery-client-enabled: false

  sleuth:
    sampler:
      probability: 1.0

  main:
    web-application-type: servlet

  application:
    name: payment

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ptarmigan
    username: root
    password: 123456
  web:
    resources:
      static-locations: classpath:/static/
      add-mappings: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379

      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 0
          max-wait: -1ms


mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.ptarmigan.payment.mapper: debug
  org.mybatis: debug
